[package]
name = "counter"
version = "0.1.0"
authors = ["Hockey <5906791+hockeyrun@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
